# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.5"

[[constraint]]
  name = "github.com/evalphobia/logrus_sentry"
  version = "0.4.5"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  branch = "master"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "1.0.6"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mesos/mesos-go"
  revision = "36b30d8a146d425c9cbd70afe86f667540a248e3"

[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/pkg/errors"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.16.12"

[[constraint]]
  name = "github.com/stretchr/testify"
  revision = "f6abca593680b2315d2075e0f5e2a9751e3f431a"

[[constraint]]
  name = "github.com/rcrowley/go-metrics"
  revision = "1f30fe9094a513ce4c700b9a54458bbb0c96996c"

[[constraint]]
  name = "github.com/cyberdelia/go-metrics-graphite"
  revision = "39f87cc3b432bbb898d7c643c0e93cac2bc865ad"

[[constraint]]
  name = "github.com/go-logfmt/logfmt"
  version = "0.3.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/time"
